Add Control Center support
enfluid/apple-audio-bar pull request #48
Opened 2017-02-27 12:07 UTC by nasakinmaxim

WIP

2017-03-01 17:22 UTC, salutis commented
In review.

2017-03-01 17:37 UTC, rudolf-adamkovic requested changes

2017-03-01 17:37 UTC, salutis commented on AudioBar/AudioBarViewController.swift
> +    private let commandCenter = MPRemoteCommandCenter.shared()
Calling this just a _Command Center_ is ambiguous.  Consider `remoteCommandCenter` at least.

2017-03-01 17:37 UTC, salutis commented on AudioBar/AudioBarViewController.swift
> +                nowPlayingInfoCenter.nowPlayingInfo![MPMediaItemPropertyPlaybackDuration] = duration
Why isn't this done declaratively in `didUpdate view`? Also, `.player` messages are for the player. It's in the name! Player only.

2017-03-01 17:37 UTC, salutis commented on AudioBar/AudioBarViewController.swift
> +                nowPlayingInfoCenter.nowPlayingInfo![MPNowPlayingInfoPropertyElapsedPlaybackTime] = time
Why isn't this done declaratively in `didUpdate view`? Also, `.player` messages are for the player. It's in the name! Player only.

2017-03-01 17:37 UTC, salutis commented on AudioBar/AudioBarViewController.swift
> +        commandCenter.playCommand.addTarget { [weak store] _ in
These commands are ridiculously complicated! We said no logic in the imperative shell and here we are.

All we want to do here is:

```swift
store!.dispatch(.remoteCommand(.userDidTapPlayButton))
```

2017-03-01 17:37 UTC, salutis commented on AudioBar/AudioBarViewController.swift
> +        commandCenter.skipForwardCommand.preferredIntervals = [.init(value: AudioBar.State.seekInterval)]
Why isn't this done declaratively in `didUpdate view`? We should not poke module's internal state really. This is why I think `static` in `State`/`View`/... is a bad idea.

2017-03-01 17:37 UTC, salutis commented on AudioBar/AudioBarViewController.swift
> +        commandCenter.skipBackwardCommand.preferredIntervals = [.init(value: AudioBar.State.seekInterval)]
Why isn't this done declaratively in `didUpdate view`? We should not poke module's internal state really. This is why I think `static` in `State`/`View`/... is a bad idea.

2017-03-01 18:32 UTC, nasakinmaxim commented on AudioBar/AudioBarViewController.swift
> +        commandCenter.playCommand.addTarget { [weak store] _ in
Do we really need `.remoreCommand` message? Can't we go with `store!.dispatch(.userDidTapPlayButton)`?

2017-03-01 23:29 UTC, salutis commented on AudioBar/AudioBarViewController.swift
> +        commandCenter.playCommand.addTarget { [weak store] _ in
Well, sure. It's a play button after all. I'm open to anything that's clean, reads well, makes sense and removes logic from the imperative shell.

2017-03-02 18:49 UTC, nasakinmaxim commented
Found some bugs with Control Center like:
* Pause button suddenly becomes play button for a couple of seconds if you tap skip forward button really fast.
* If you tap skip backward button really fast at the beginning of an audio file (first ~5 seconds), the elapsed playback time won't change.

They also appear in Apple Podcasts app.
Because of them and the fact that `MPRemoteControlCenter` automatically handles `AVPlayer` (which we don't want), I had to use blocks instead of adding a selector to rewrite behaviors in https://github.com/enfluid/apple-audio-bar/pull/48/commits/3f7e23c8369b22cd36d75e8d1adb1fda9a53ce30.

2017-03-02 21:56 UTC, salutis commented
In review.

2017-03-02 22:01 UTC, salutis commented on AudioBar/AudioBarViewController.swift
> +                nowPlayingInfoCenter.nowPlayingInfo![MPMediaItemPropertyPlaybackDuration] = duration
This wasn't addressed. Why is this an action instead of a view property?

2017-03-02 22:01 UTC, salutis commented on AudioBar/AudioBarViewController.swift
> +                nowPlayingInfoCenter.nowPlayingInfo![MPNowPlayingInfoPropertyElapsedPlaybackTime] = time
This wasn't addressed. Why is this an action instead of a view property?

2017-03-02 22:08 UTC, rudolf-adamkovic requested changes
Not everything was addressed.

2017-03-03 17:33 UTC, nasakinmaxim commented
@salutis
I used `Action.NowPlayingInfoCenter` to set values in `MPNowPlayingInfoCenter` when needed. Setting them using `View` shows bad performance (the elapsed playback time doesn't update as soon as we need it to, sometimes player stops for a few seconds).
Tested on iPhone 5S.

2017-03-06 10:07 UTC, salutis commented
@nasakinmaxim 

> Setting them using `View` shows bad performance [...]

Can you push this on a `spike` branch so that I can take a look?

2017-03-06 16:00 UTC, nasakinmaxim commented
@salutis
Sure.
To clarify my point, I'll post some gifs.
Here's how it works when updating `MPNowPlayingInfoCenter` using `Action`:
![action](https://cloud.githubusercontent.com/assets/8248974/23617661/d56093ca-029e-11e7-9072-d715f381e6b1.gif)
Here's how it works with `View`:
![view](https://cloud.githubusercontent.com/assets/8248974/23617720/0d61e6f2-029f-11e7-987d-26daf2c8aad3.gif)

2017-03-06 16:31 UTC, salutis commented
Investigating.

2017-03-06 16:39 UTC, salutis commented
I don't like the idea of polluting our functional core just because Apple's code is buggy. Let's patch buggy `MPNowPlayingInfoCenter` instead:

```swift
extension MPNowPlayingInfoCenter {

    func setElapsedPlaybackTime(_ elapsedPlaybackTime: TimeInterval) {
        guard needsSetElapsedPlaybackTime(elapsedPlaybackTime) else { return }
        forceSetElapsedPlaybackTime(elapsedPlaybackTime)
    }

    private func needsSetElapsedPlaybackTime(_ elapsedPlaybackTime: TimeInterval) -> Bool {
        return nowPlayingInfo?[MPNowPlayingInfoPropertyElapsedPlaybackTime] as? TimeInterval != elapsedPlaybackTime
    }

    private func forceSetElapsedPlaybackTime(_ elapsedPlaybackTime: TimeInterval) {
        nowPlayingInfo![MPNowPlayingInfoPropertyElapsedPlaybackTime] = elapsedPlaybackTime
    }

}
```

```swift
extension MPNowPlayingInfoCenter {

    func setPlaybackDuration(_ playbackDuration: TimeInterval) {
        guard needsPlaybackDuration(playbackDuration) else { return }
        forceSetPlaybackDuration(playbackDuration)
    }

    private func needsPlaybackDuration(_ playbackDuration: TimeInterval) -> Bool {
        return nowPlayingInfo?[MPMediaItemPropertyPlaybackDuration] as? TimeInterval != playbackDuration
    }

    private func forceSetPlaybackDuration(_ playbackDuration: TimeInterval) {
        nowPlayingInfo![MPMediaItemPropertyPlaybackDuration] = playbackDuration
    }

}
```

```swift
public func store(_ store: Store<AudioBar>, didUpdate view: AudioBar.View) {
    ...
    nowPlayingInfoCenter.setElapsedPlaybackTime(view.elapsedPlaybackTime)
    nowPlayingInfoCenter.setPlaybackDuration(view.totalPlaybackTime)
}
```

2017-03-06 16:52 UTC, nasakinmaxim commented
@salutis
As usual, great idea!
I'm on it.

2017-03-07 11:21 UTC, salutis commented
In review.

2017-03-07 12:00 UTC, rudolf-adamkovic requested changes

2017-03-07 12:00 UTC, salutis commented on AudioBar/AudioBarTests.swift
> +    func testPlaybackDuration1() {
Why do we have 4 tests for durations 1, 20, 21 and 60 seconds? We need just two — 1 and 2 seconds.

2017-03-07 12:00 UTC, salutis commented on AudioBar/AudioBarTests.swift
> +    func testElapsedPlaybackTime1() {
Why do we have 4 tests for `nil`, 0, 1 and 20 seconds? We need just three — `nil`, 1 and 2 seconds.

2017-03-07 12:00 UTC, salutis commented on AudioBar/AudioBarTests.swift
> +    func testPlayAndPauseCommandsEnabled1() {
This needs to be split.

2017-03-07 12:00 UTC, salutis commented on AudioBar/AudioBarTests.swift
> +    func testPlayAndPauseCommandsEnabled2() {
This needs to be split.

2017-03-07 12:00 UTC, salutis commented on AudioBar/AudioBarTests.swift
> +    func testPlayAndPauseCommandsEnabled3() {
This needs to be split.

2017-03-07 12:00 UTC, salutis commented on AudioBar/AudioBarTests.swift
> +        let view = expectView(for: .readyToPlay(.init(isPlaying: false)))
Both `isPlayCommandEnabled` and `isPauseCommandEnabled` are derived not only from `isPlaying` and `isPlayPauseButtonEnabled`. In turn, `isPlayPauseButtonEnabled` is derived from `remainingTime` and that one is derived from `currentTime` and `duration`.

In unit tests, we have the following default initializer:

```swift
extension AudioBar.State.ReadyToPlay {
    init(isPlaying: Bool = false, duration: TimeInterval = 60, currentTime: TimeInterval? = nil) { ... }
}
```

I should be able to change all three arguments  — `isPlaying`, `duration` and `currentTime` — without any tests failing. When I change `currentTime` to `60`, this test fails. This means, you rely on "random data" we use there.

2017-03-07 12:00 UTC, salutis commented on AudioBar/MPNowPlayingInfoCenterPatches.swift
> +extension MPNowPlayingInfoCenter {
We can split this into two files:

* `MPNowPlayingInfoCenter+ElapsedPlaybackTime.swift`
* `MPNowPlayingInfoCenter+PlaybackDuration.swift`

Once done, we don't need `MARK` comments.

2017-03-07 17:53 UTC, salutis commented
In review.

2017-03-07 17:56 UTC, rudolf-adamkovic approved these changes
Great work!

2017-03-07 17:56 UTC, merged