Split "togglePlay" message
enfluid/apple-audio-bar pull request #49
Opened 2017-02-27 15:33 UTC by nasakinmaxim

2017-02-27 17:44 UTC, salutis commented
In review.

2017-02-27 18:00 UTC, rudolf-adamkovic requested changes

2017-02-27 18:00 UTC, salutis commented on AudioBar/AudioBarViewController.swift
> +        switch program.view.playPauseButtonMode {
Consider replacing `playPauseButtonMode` with `playPauseButtonMessage`, e.g.:

```swift
let message = program.view.playPauseButtonMessage
program.dispatch(message)
```

2017-02-27 18:49 UTC, nasakinmaxim commented on AudioBar/AudioBarViewController.swift
> +        switch program.view.playPauseButtonMode {
Did a different implementation since we don't won't to have any message in `program.view.playPauseButtonMessage`.

2017-02-28 12:46 UTC, salutis commented
In review.

2017-02-28 12:48 UTC, rudolf-adamkovic requested changes

2017-02-28 12:48 UTC, salutis commented on AudioBar/AudioBarViewController.swift
> +        program.dispatch(.playPauseButton(mode))
My original suggestion was about exposing a "callback" message in `View`.

This is much more complicated.

2017-02-28 21:27 UTC, salutis commented
In review.

2017-02-28 21:39 UTC, salutis commented
Looks good. Waiting Emotion Code PR to try this out. Once done, I will test and approve.

2017-02-28 22:05 UTC, rudolf-adamkovic approved these changes

2017-02-28 22:05 UTC, merged

2017-02-28 22:05 UTC, salutis commented
@nasakinmaxim Fantastic work here! Thank you.