Release 0.6.0 to master
enfluid/apple-audio-bar pull request #68
Opened 2017-03-09 13:23 UTC by salutis

2017-03-09 13:39 UTC, andris-zalitis commented
In review

2017-03-09 13:41 UTC, andris-zalitis requested changes
So which version is it going to be? :)

2017-03-09 13:41 UTC, andris-zalitis commented on AudioBar/Info.plist
> +	<string>0.5.3</string>
PR title says it's 0.6.0

2017-03-09 18:01 UTC, salutis commented on AudioBar/Info.plist
> +	<string>0.5.3</string>
Oooooooops.

2017-03-10 09:34 UTC, andris-zalitis approved these changes
LGTM! :)

2017-03-10 09:34 UTC, merged