Write initial implementation
enfluid/apple-audio-bar pull request #7
Opened 2016-12-15 18:15 UTC by salutis

2016-12-15 18:46 UTC, salutis commented
@andris-zalitis FYI: 
* Not localized for now. We need to figure out how to test it.
* Big switch statements. We need to solve this in the Elm framework itself.

2016-12-16 12:15 UTC, andris-zalitis commented
In review

2016-12-17 22:23 UTC, andris-zalitis requested changes
@salutis 
I really like this. Tests are super simple to read and reason about. 👍 I have added some comments regarding possible improvements some of which we already have spoken about.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+LoadTrack.swift
> +    func testLoadTrackUnexpectedly() {}
It would be great if we had an issue on GitHub regarding this TODO.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+SeekBack.swift
> +
Please consider adding a test for Model.waitingForPlayerToBecomeReadyToPlayURL to cover all invalid cases in tests for consistency.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBar/AudioBarModule.swift
> +                guard let currentTime = state.currentTime else { return false }
Not tested.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBar/AudioBarModule.swift
> +                guard let remainingTime = remainingTime else { return false }
Not tested

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBar/AudioBarModule.swift
> +                guard let remainingTime = remainingTime else { return true }
Not tested

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+PlayPauseButton.swift
> +    func testPlayButtonDisabledWhenNoTimeRemaining() {
Please, consider changing the name to `testPlayPauseButtonDisabledWhenNoTimeRemaining`.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBar/AudioBarModule.swift
> +        case togglePlay
Please consider changing the code so that instead of `.togglePlay` we would have two `Message`s `.play` and `.pause`. This would make it easier to understand what happens in `func update`.

Currently, in `func update` when looking at a case `Model.waitingForPlayerToBecomeReadyToPlayURL` we must keep in mind that to get there user must have pressed play once, so `tooglePlay` means **pause** now. If we'd have `.pause` and `.play`, no such reasoning would be necessary.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+DefaultModel.swift
> +extension Tests {
Since we're not using any common functionality of `Tests`, please consider using a separate class instead of an extension.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+InitialViews.swift
> +extension Tests {
Please consider using a separate class instead of an extension.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+LoadTrack.swift
> +extension Tests {
Please consider using a separate class instead of an extension.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+LoadingIndicator.swift
> +extension Tests {
Please consider using a separate class instead of an extension.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+PlayPauseButton.swift
> +extension Tests {
Please consider using a separate class instead of an extension.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+PlaybackTime.swift
> +extension Tests {
Please consider using a separate class instead of an extension.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+PlayerFailed.swift
> +extension Tests {
Please consider using a separate class instead of an extension.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+PlayerFinished.swift
> +extension Tests {
Please consider using a separate class instead of an extension.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+PlayerReady.swift
> +extension Tests {
Please consider using a separate class instead of an extension.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+PlayerTime.swift
> +extension Tests {
Please consider using a separate class instead of an extension.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+SeekBack.swift
> +extension Tests {
Please consider using a separate class instead of an extension.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+SeekBackButton.swift
> +extension Tests {
Please consider using a separate class instead of an extension.

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+SeekForward.swift
> +    func testSeekBackWhenNotAllowed1() {
Shouldn't this be moved to `Tests+SeekBack.swift`?

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+SeekForward.swift
> +    func testSeekBackWhenNotAllowed2() {
Shouldn't this be moved to `Tests+SeekBack.swift`?

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+SeekBack.swift
> +    func testSeekForwardWhenNotAllowed1() {
Shouldn't this be moved to `Tests+SeekForward.swift`?

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+SeekBack.swift
> +    func testSeekForwardWhenNotAllowed2() {
Shouldn't this be moved to `Tests+SeekForward.swift`?

2016-12-17 22:23 UTC, andris-zalitis commented on Sources/AudioBarTests/Tests+SeekForward.swift
> +
Please consider adding a test for Model.waitingForPlayerToBecomeReadyToPlayURL to cover all invalid cases in tests for consistency.

2016-12-19 10:25 UTC, salutis commented
@andris-zalitis Thanks for a fantastic code review! Addressed all issues and more. Ready to be reviewed once again!

2016-12-19 15:50 UTC, andris-zalitis requested changes
Looks good! I found just one tiny thing in imperative shell code.

2016-12-19 15:50 UTC, andris-zalitis commented on AudioBar/AudioBarViewController.swift
> +        if let playerItem = player.currentItem, keyPath == #keyPath(AVPlayerItem.status) {
It would be safer if we made sure also that object is `player.currentItem`.

2016-12-19 15:56 UTC, salutis commented on AudioBar/AudioBarViewController.swift
> +        if let playerItem = player.currentItem, keyPath == #keyPath(AVPlayerItem.status) {
Fixed.

2016-12-20 13:24 UTC, andris-zalitis approved these changes

2016-12-20 13:26 UTC, merged